name: playerOperationSychronize
main: me.ironblock.playerOperationSychronize.Main
version: 1.0
api-version: 1.17
author: Iron__Block
commands:
  pluginStart:
    description: 开始
  pluginStop:
    description: 停止
  nextOperator:
    description: 立即让下个人是控制者
  setOperator:
    description: 设置指定玩家为控制者
  setOperatorChangeTime:
    description: 设置轮换控制者的时间
  setLoopMode:
    description: 设置循环方式 0->单人轮流控制,1->先单人轮流控制,然后多人同时控制,2->多人同时控制
  resetAll:
    description: 重置客户端的所有状态
  resetKey:
    description: 重置客户端的按键状态
  pluginHelp:
    description: 打印插件的帮助文件
  testPlayer:
    description: aasad